services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace/frontend
    command: "npm start -- --host 0.0.0.0 --port 4200"
    ports:
      - 127.0.0.1:4200:4200
    volumes:
      - ./:/workspace
      - /workspace/frontend/node_modules